import knex, { Knex } from 'knex';
import dotenv from 'dotenv';
import { Basin, GlacialLake, FloodAlert, HydropowerPlantCascade, DHMHydrometricStation, HistoricalGLOFRecord } from '../types';

dotenv.config();

const connectionString =
  process.env.DATABASE_URL ||
  'postgresql://ews_admin:ews_secure_password@localhost:5435/himalaya_ews';

export const db: Knex = knex({
  client: 'pg',
  connection: connectionString,
  pool: {
    min: 2,
    max: 20,
    acquireTimeoutMillis: 10000,
    createTimeoutMillis: 5000,
    idleTimeoutMillis: 30000,
  },
  acquireConnectionTimeout: 10000,
});

/**
 * Validates database connectivity and PostGIS extension health.
 */
export async function checkDatabaseHealth(): Promise<{ status: 'healthy' | 'degraded' | 'offline'; postgis_version?: string; latency_ms: number; error?: string }> {
  const start = Date.now();
  try {
    const result = await db.raw('SELECT PostGIS_Version() as postgis, NOW() as server_time');
    const latency = Date.now() - start;
    return {
      status: 'healthy',
      postgis_version: result.rows?.[0]?.postgis || '3.4',
      latency_ms: latency,
    };
  } catch (err: any) {
    return {
      status: 'degraded',
      latency_ms: Date.now() - start,
      error: err.message || 'Database unavailable',
    };
  }
}

// Fallback In-Memory Datastores (for offline dev and mock testing)
export const MOCK_BASINS: Basin[] = [
  { id: 'b1111111-1111-1111-1111-111111111111', name: 'Koshi' },
  { id: 'b2222222-2222-2222-2222-222222222222', name: 'Gandaki' },
  { id: 'b3333333-3333-3333-3333-333333333333', name: 'Karnali' },
  { id: 'b4444444-4444-4444-4444-444444444444', name: 'Mahakali' },
];

export const MOCK_GLACIAL_LAKES: GlacialLake[] = [
  {
    id: 'l1111111-1111-1111-1111-111111111111',
    icimod_code: 'PDGL_NEP_KOSHI_001',
    name: 'Tsho Rolpa',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 1540000,
    danger_level: 'CRITICAL',
    centroid: { type: 'Point', coordinates: [86.475, 27.868] },
  },
  {
    id: 'l2222222-2222-2222-2222-222222222222',
    icimod_code: 'PDGL_NEP_KOSHI_002',
    name: 'Imja Tsho',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 1280000,
    danger_level: 'HIGH',
    centroid: { type: 'Point', coordinates: [86.924, 27.910] },
  },
  {
    id: 'l4444444-4444-4444-4444-444444444444',
    icimod_code: 'PDGL_NEP_KOSHI_003',
    name: 'Lower Barun Lake',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 1720000,
    danger_level: 'HIGH',
    centroid: { type: 'Point', coordinates: [87.102, 27.808] },
  },
  {
    id: 'l-lumding',
    icimod_code: 'PDGL_NEP_KOSHI_004',
    name: 'Lumding Tsho',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 1050000,
    danger_level: 'HIGH',
    centroid: { type: 'Point', coordinates: [86.612, 27.765] },
  },
  {
    id: 'l-chamlang',
    icimod_code: 'PDGL_NEP_KOSHI_005',
    name: 'Chamlang Tsho (Hongu-2)',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 910000,
    danger_level: 'HIGH',
    centroid: { type: 'Point', coordinates: [86.974, 27.782] },
  },
  {
    id: 'l-dig-tsho',
    icimod_code: 'PDGL_NEP_KOSHI_006',
    name: 'Dig Tsho (1985 Breach)',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 680000,
    danger_level: 'MEDIUM',
    centroid: { type: 'Point', coordinates: [86.584, 27.876] },
  },
  {
    id: 'l-galong-co',
    icimod_code: 'PDGL_NEP_KOSHI_007',
    name: 'Galong Co / Cirenmaco (Poiqu Transboundary)',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 1580000,
    danger_level: 'CRITICAL',
    centroid: { type: 'Point', coordinates: [86.068, 28.066] },
  },
  {
    id: 'l3333333-3333-3333-3333-333333333333',
    icimod_code: 'PDGL_NEP_GANDAKI_001',
    name: 'Thulagi Lake',
    basin_id: 'b2222222-2222-2222-2222-222222222222',
    basin_name: 'Gandaki',
    initial_area_sqm: 940000,
    danger_level: 'HIGH',
    centroid: { type: 'Point', coordinates: [84.532, 28.517] },
  },
  {
    id: 'l-birendra',
    icimod_code: 'PDGL_NEP_GANDAKI_002',
    name: 'Birendra Lake (Manaslu)',
    basin_id: 'b2222222-2222-2222-2222-222222222222',
    basin_name: 'Gandaki',
    initial_area_sqm: 350000,
    danger_level: 'CRITICAL',
    centroid: { type: 'Point', coordinates: [84.638, 28.563] },
  },
  {
    id: 'l-kaldang',
    icimod_code: 'PDGL_NEP_GANDAKI_003',
    name: 'Kaldang Lake (Langtang)',
    basin_id: 'b2222222-2222-2222-2222-222222222222',
    basin_name: 'Gandaki',
    initial_area_sqm: 590000,
    danger_level: 'MEDIUM',
    centroid: { type: 'Point', coordinates: [85.485, 28.215] },
  },
  {
    id: 'l5555555-5555-5555-5555-555555555555',
    icimod_code: 'PDGL_NEP_KARNALI_001',
    name: 'Karnali High-Alpine Glacial Lake',
    basin_id: 'b3333333-3333-3333-3333-333333333333',
    basin_name: 'Karnali',
    initial_area_sqm: 680000,
    danger_level: 'LOW',
    centroid: { type: 'Point', coordinates: [82.342, 29.893] },
  },
  {
    id: 'l-rara-headwater',
    icimod_code: 'PDGL_NEP_KARNALI_002',
    name: 'Rara Headwater Glacial Lake',
    basin_id: 'b3333333-3333-3333-3333-333333333333',
    basin_name: 'Karnali',
    initial_area_sqm: 510000,
    danger_level: 'LOW',
    centroid: { type: 'Point', coordinates: [82.115, 29.542] },
  },
  {
    id: 'l-api-nampa-srv',
    icimod_code: 'PDGL_NEP_MAHAKALI_001',
    name: 'Api Nampa Proglacial Lake',
    basin_id: 'b4444444-4444-4444-4444-444444444444',
    basin_name: 'Mahakali',
    initial_area_sqm: 420000,
    danger_level: 'LOW',
    centroid: { type: 'Point', coordinates: [80.950, 29.980] },
  },
  {
    id: 'l-south-lhonak',
    icimod_code: 'PDGL_IND_SIKKIM_001',
    name: 'South Lhonak Lake (2023 Benchmark)',
    basin_id: 'b1111111-1111-1111-1111-111111111111',
    basin_name: 'Koshi',
    initial_area_sqm: 810000,
    danger_level: 'CRITICAL',
    centroid: { type: 'Point', coordinates: [88.196, 27.912] },
  },
];

export const MOCK_HYDROPOWER_CASCADES: HydropowerPlantCascade[] = [
  {
    id: 'hp-upper-tamakoshi',
    name: 'Upper Tamakoshi Hydroelectric Project',
    operator: 'Upper Tamakoshi Hydropower Limited (UTKHPL / NEA)',
    capacity_mw: 456,
    river: 'Tama Koshi',
    basin: 'Koshi',
    coordinates: [86.220, 27.700],
    headpond_volume_m3: 1200000,
    upstream_threat_lake_id: 'l1111111-1111-1111-1111-111111111111',
    upstream_threat_lake_name: 'Tsho Rolpa',
    lead_time_minutes: 48,
    scada_ip: '192.168.10.45',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 4,
    drawdown_buffer_m: 4.5,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-arun-3',
    name: 'Arun III Hydroelectric Project',
    operator: 'SJVN Arun-3 Power Development Company (SAPDC)',
    capacity_mw: 900,
    river: 'Arun',
    basin: 'Koshi',
    coordinates: [87.210, 27.530],
    headpond_volume_m3: 4800000,
    upstream_threat_lake_id: 'l4444444-4444-4444-4444-444444444444',
    upstream_threat_lake_name: 'Lower Barun Lake',
    lead_time_minutes: 85,
    scada_ip: '192.168.12.90',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 6,
    drawdown_buffer_m: 8.0,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-upper-bhotekoshi',
    name: 'Upper Bhote Koshi Hydroelectric Project',
    operator: 'Bhote Koshi Power Company (BKPC)',
    capacity_mw: 45,
    river: 'Bhote Koshi',
    basin: 'Koshi',
    coordinates: [85.935, 27.910],
    headpond_volume_m3: 350000,
    upstream_threat_lake_id: 'l-galong-co',
    upstream_threat_lake_name: 'Galong Co / Cirenmaco',
    lead_time_minutes: 22,
    scada_ip: '192.168.14.20',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 3,
    drawdown_buffer_m: 2.5,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-middle-bhotekoshi',
    name: 'Middle Bhotekoshi Hydroelectric Project',
    operator: 'Madhya Bhotekoshi Jalavidyut Co.',
    capacity_mw: 102,
    river: 'Bhote Koshi',
    basin: 'Koshi',
    coordinates: [85.890, 27.840],
    headpond_volume_m3: 680000,
    upstream_threat_lake_id: 'l-dig-tsho',
    upstream_threat_lake_name: 'Dig Tsho (Langmoche)',
    lead_time_minutes: 38,
    scada_ip: '192.168.14.55',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 4,
    drawdown_buffer_m: 3.2,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-upper-trishuli-1',
    name: 'Upper Trishuli-1 Hydroelectric Project',
    operator: 'NWEDC / Korea South-East Power',
    capacity_mw: 216,
    river: 'Trishuli',
    basin: 'Gandaki',
    coordinates: [85.240, 28.110],
    headpond_volume_m3: 1800000,
    upstream_threat_lake_id: 'l-kaldang',
    upstream_threat_lake_name: 'Kaldang Lake',
    lead_time_minutes: 55,
    scada_ip: '192.168.16.10',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 4,
    drawdown_buffer_m: 5.0,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-middle-marsyangdi',
    name: 'Middle Marsyangdi Hydropower Station',
    operator: 'Nepal Electricity Authority (NEA)',
    capacity_mw: 70,
    river: 'Marsyangdi',
    basin: 'Gandaki',
    coordinates: [84.380, 28.180],
    headpond_volume_m3: 950000,
    upstream_threat_lake_id: 'l3333333-3333-3333-3333-333333333333',
    upstream_threat_lake_name: 'Thulagi Lake',
    lead_time_minutes: 62,
    scada_ip: '192.168.18.30',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 3,
    drawdown_buffer_m: 3.8,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-marsyangdi',
    name: 'Marsyangdi Hydropower Station (Anbu Khaireni)',
    operator: 'Nepal Electricity Authority (NEA)',
    capacity_mw: 69,
    river: 'Marsyangdi',
    basin: 'Gandaki',
    coordinates: [84.510, 27.980],
    headpond_volume_m3: 1100000,
    upstream_threat_lake_id: 'l3333333-3333-3333-3333-333333333333',
    upstream_threat_lake_name: 'Thulagi Lake',
    lead_time_minutes: 74,
    scada_ip: '192.168.18.60',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 4,
    drawdown_buffer_m: 4.0,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
  {
    id: 'hp-budhi-gandaki',
    name: 'Budhi Gandaki Hydroelectric Project',
    operator: 'Budhi Gandaki Hydro Power Company Limited',
    capacity_mw: 1200,
    river: 'Budhi Gandaki',
    basin: 'Gandaki',
    coordinates: [84.820, 27.950],
    headpond_volume_m3: 15200000,
    upstream_threat_lake_id: 'l-birendra',
    upstream_threat_lake_name: 'Birendra Lake',
    lead_time_minutes: 42,
    scada_ip: '192.168.20.10',
    scada_protocol: 'IEC 60870-5-104',
    radial_gates_count: 8,
    drawdown_buffer_m: 12.0,
    interlock_status: 'MONITORING',
    last_tripped_at: null,
    last_command_hex: null,
  },
];

export const MOCK_DHM_STATIONS: DHMHydrometricStation[] = [
  {
    id: 'dhm-680',
    station_number: 680,
    name: 'Gongar Khola at Tama Koshi',
    river: 'Tama Koshi',
    basin: 'Koshi',
    elevation_m: 1690,
    coordinates: [86.225, 27.705],
    sensor_type: 'RADAR_STAGE',
    current_stage_m: 2.85,
    warning_stage_m: 4.5,
    danger_stage_m: 6.0,
    current_discharge_cms: 115.0,
    status: 'NORMAL',
    telemetry_source: 'DHM_TELEMETRIC_NETWORK',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-670',
    station_number: 670,
    name: 'Sun Koshi at Rabuwa Bazar',
    river: 'Sun Koshi',
    basin: 'Koshi',
    elevation_m: 540,
    coordinates: [86.580, 27.240],
    sensor_type: 'ULTRASONIC_SURGE',
    current_stage_m: 4.12,
    warning_stage_m: 7.0,
    danger_stage_m: 9.5,
    current_discharge_cms: 340.0,
    status: 'NORMAL',
    telemetry_source: 'DHM_TELEMETRIC_NETWORK',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-679',
    station_number: 679,
    name: 'Rolwaling Khola at Simigaon',
    river: 'Rolwaling Khola',
    basin: 'Koshi',
    elevation_m: 2020,
    coordinates: [86.340, 27.770],
    sensor_type: 'RADAR_STAGE',
    current_stage_m: 1.62,
    warning_stage_m: 2.8,
    danger_stage_m: 4.0,
    current_discharge_cms: 42.0,
    status: 'NORMAL',
    telemetry_source: 'DHM_TELEMETRIC_NETWORK',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-447',
    station_number: 447,
    name: 'Trishuli River at Betrawati',
    river: 'Trishuli',
    basin: 'Gandaki',
    elevation_m: 620,
    coordinates: [85.180, 27.970],
    sensor_type: 'PRESSURE_TRANSDUCER',
    current_stage_m: 3.40,
    warning_stage_m: 5.5,
    danger_stage_m: 7.5,
    current_discharge_cms: 195.0,
    status: 'NORMAL',
    telemetry_source: 'DHM_TELEMETRIC_NETWORK',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-439',
    station_number: 439,
    name: 'Marsyangdi at Bimalnagar',
    river: 'Marsyangdi',
    basin: 'Gandaki',
    elevation_m: 380,
    coordinates: [84.450, 27.970],
    sensor_type: 'RADAR_STAGE',
    current_stage_m: 3.10,
    warning_stage_m: 5.8,
    danger_stage_m: 8.0,
    current_discharge_cms: 210.0,
    status: 'NORMAL',
    telemetry_source: 'DHM_TELEMETRIC_NETWORK',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-445',
    station_number: 445,
    name: 'Budhi Gandaki at Arughat',
    river: 'Budhi Gandaki',
    basin: 'Gandaki',
    elevation_m: 510,
    coordinates: [84.810, 28.050],
    sensor_type: 'RADAR_STAGE',
    current_stage_m: 2.95,
    warning_stage_m: 6.0,
    danger_stage_m: 8.5,
    current_discharge_cms: 185.0,
    status: 'NORMAL',
    telemetry_source: 'DHM_TELEMETRIC_NETWORK',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-280',
    station_number: 280,
    name: 'Karnali River at Asaraghat',
    river: 'Karnali',
    basin: 'Karnali',
    elevation_m: 660,
    coordinates: [81.560, 29.080],
    sensor_type: 'RADAR_STAGE',
    current_stage_m: 4.80,
    warning_stage_m: 8.5,
    danger_stage_m: 11.0,
    current_discharge_cms: 460.0,
    status: 'NORMAL',
    telemetry_source: 'GOES_SATELLITE',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'dhm-120',
    station_number: 120,
    name: 'Mahakali River at Darchula',
    river: 'Mahakali',
    basin: 'Mahakali',
    elevation_m: 890,
    coordinates: [80.540, 29.840],
    sensor_type: 'RADAR_STAGE',
    current_stage_m: 3.25,
    warning_stage_m: 6.5,
    danger_stage_m: 9.0,
    current_discharge_cms: 220.0,
    status: 'NORMAL',
    telemetry_source: 'GOES_SATELLITE',
    last_updated: new Date().toISOString(),
  },
];

export const MOCK_HISTORICAL_GLOFS: HistoricalGLOFRecord[] = [
  {
    id: 'glof-bhotekoshi-2026',
    event_name: 'Bhotekoshi–Trishuli Glacial Avalanche & Outburst Surge (August 26, 2026)',
    lake_or_glacier: 'Langtang–Tibet Border Glacial Cirque',
    basin: 'Gandaki / Koshi',
    river: 'Bhotekoshi & Trishuli River System',
    country_region: 'Nepal–Tibet Border / Rasuwa, Nuwakot & Dhading',
    event_date: '2026-08-26',
    year: 2026,
    coordinates: [85.340, 28.320],
    trigger_mechanism: 'ROCK_ICE_DETACHMENT',
    estimated_volume_m3: 25000000,
    peak_discharge_cms: 8800,
    downstream_impact_km: 85,
    fatalities: 1290,
    infrastructure_impact: 'Devastating high-velocity slurry surge washing away 2.2 million tonnes of debris, obliterating road spans along Pasang Lhamu Highway, severing Rasuwagadhi border trade point, and causing severe siltation and structural damage to Upper Trishuli-1 and Bhotekoshi hydropower installations.',
    key_findings: 'Compound multi-hazard cascade: hanging glacial ice and rock detachment dammed an upper transboundary canyon, creating a transient barrier impoundment that burst catastrophically. Highlighted vital need for transboundary seismic tripwires and automated SCADA gate opening within 15 minutes.'
  },
  {
    id: 'glof-dig-tsho-1985',
    event_name: 'Dig Tsho GLOF (1985)',
    lake_or_glacier: 'Dig Tsho / Langmoche Glacier',
    basin: 'Koshi',
    river: 'Langmoche Khola / Dudh Koshi',
    country_region: 'Solukhumbu, Nepal',
    event_date: '1985-08-04',
    year: 1985,
    coordinates: [86.584, 27.876],
    trigger_mechanism: 'ICE_AVALANCHE',
    estimated_volume_m3: 5100000,
    peak_discharge_cms: 1600,
    downstream_impact_km: 90,
    fatalities: 4,
    infrastructure_impact: 'Completely destroyed the nearly completed Namche Small Hydropower plant (US$ 3M), 14 bridges, 30 houses, and severe river morphology alteration.',
    key_findings: 'Ice avalanche detached from Langmoche peak into terminal moraine, sending a 4m displacement wave that breached the ice-cored moraine dam within 4 hours.'
  },
  {
    id: 'glof-tam-pokhari-1998',
    event_name: 'Tam Pokhari (Sabai Tsho) GLOF (1998)',
    lake_or_glacier: 'Tam Pokhari / Sabai Glacier',
    basin: 'Koshi',
    river: 'Hinku Khola / Dudh Koshi',
    country_region: 'Solukhumbu, Nepal',
    event_date: '1998-09-03',
    year: 1998,
    coordinates: [86.878, 27.742],
    trigger_mechanism: 'ICE_AVALANCHE',
    estimated_volume_m3: 18000000,
    peak_discharge_cms: 10000,
    downstream_impact_km: 120,
    fatalities: 2,
    infrastructure_impact: 'Destroyed 6 suspension bridges along the Dudh Koshi trekker corridor, washed away riverside lodges, agricultural terraces, and trail networks.',
    key_findings: 'Failure of moraine dam due to hanging glacier icefall creating massive dynamic wave run-up overtopping the freeboard.'
  },
  {
    id: 'glof-cirenmaco-1981',
    event_name: 'Cirenmaco / Zhangzangbo Transboundary GLOF (1981)',
    lake_or_glacier: 'Cirenmaco Lake / Poiqu Basin',
    basin: 'Koshi',
    river: 'Poiqu / Bhote Koshi / Sun Koshi',
    country_region: 'Tibet (China) & Bagmati/Koshi (Nepal)',
    event_date: '1981-07-11',
    year: 1981,
    coordinates: [86.068, 28.066],
    trigger_mechanism: 'MORAINE_COLLAPSE',
    estimated_volume_m3: 19000000,
    peak_discharge_cms: 16000,
    downstream_impact_km: 65,
    fatalities: 73,
    infrastructure_impact: 'Completely destroyed the Sino-Nepal Friendship Bridge at Kodari, washed away 27 km of the Arniko Highway, wiped out Sun Koshi Hydropower intake.',
    key_findings: 'Transboundary cascade risk: moraine dam collapsed catastrophically within 1 hour. Highlights urgent requirement for cross-border telemetry.'
  },
  {
    id: 'glof-lugge-tsho-1994',
    event_name: 'Lugge Tsho GLOF (1994)',
    lake_or_glacier: 'Lugge Tsho / Lunana Ice Complex',
    basin: 'Koshi-adjacent',
    river: 'Pho Chhu River',
    country_region: 'Lunana, Bhutan (Eastern Himalaya border)',
    event_date: '1994-10-07',
    year: 1994,
    coordinates: [90.301, 28.112],
    trigger_mechanism: 'PIPING_FAILURE',
    estimated_volume_m3: 17200000,
    peak_discharge_cms: 2500,
    downstream_impact_km: 95,
    fatalities: 21,
    infrastructure_impact: 'Severely flooded Punakha Dzong, devastated riverside communities, washed away historic timber bridges and agricultural terraces.',
    key_findings: 'Internal moraine piping and buried ice core degradation; prompted deployment of early warning manual acoustic observers and automated sensors.'
  },
  {
    id: 'glof-south-lhonak-2023',
    event_name: 'South Lhonak Lake GLOF & Teesta III Breach (2023)',
    lake_or_glacier: 'South Lhonak Lake',
    basin: 'Koshi / Teesta',
    river: 'Teesta River',
    country_region: 'North Sikkim, Eastern Himalaya',
    event_date: '2023-10-04',
    year: 2023,
    coordinates: [88.196, 27.912],
    trigger_mechanism: 'EXTREME_CLOUDBURST',
    estimated_volume_m3: 14000000,
    peak_discharge_cms: 15000,
    downstream_impact_km: 110,
    fatalities: 102,
    infrastructure_impact: 'Completely swept away the 1,200 MW Chungthang (Teesta III) Hydro Dam, 14 bridges, National Highway 10, Army camp at Bardang.',
    key_findings: 'Extreme cloudburst induced a lateral moraine slump into the lake. Lack of automated SCADA interlocks at Teesta III led to dam overtopping.'
  },
  {
    id: 'glof-birendra-2024',
    event_name: 'Birendra Lake Avalanche Displacement Surge (2024)',
    lake_or_glacier: 'Birendra Lake / Mt. Manaslu North Glacier',
    basin: 'Gandaki',
    river: 'Budhi Gandaki River',
    country_region: 'Samagaon, Gorkha, Nepal',
    event_date: '2024-04-21',
    year: 2024,
    coordinates: [84.638, 28.563],
    trigger_mechanism: 'ICE_AVALANCHE',
    estimated_volume_m3: 1800000,
    peak_discharge_cms: 850,
    downstream_impact_km: 45,
    fatalities: 0,
    infrastructure_impact: 'Washed away wooden pedestrian bridge at Samagaon, damaged river trail to Larkya La, triggered downstream emergency evacuation.',
    key_findings: 'Hanging serac detachment from Manaslu slope into proglacial lake. Zero casualties achieved thanks to community radio and daytime visibility.'
  },
  {
    id: 'glof-seti-river-2012',
    event_name: 'Seti River Catastrophic Surge & Debris Flow (2012)',
    lake_or_glacier: 'Annapurna IV Glacial Cirque',
    basin: 'Gandaki',
    river: 'Seti River',
    country_region: 'Kaski / Pokhara Valley, Nepal',
    event_date: '2012-05-05',
    year: 2012,
    coordinates: [84.050, 28.450],
    trigger_mechanism: 'ROCK_ICE_DETACHMENT',
    estimated_volume_m3: 32000000,
    peak_discharge_cms: 4500,
    downstream_impact_km: 40,
    fatalities: 72,
    infrastructure_impact: 'Washed away entire settlement of Kharapani, hot spring tourism complex, 2 suspension bridges, submerged heavy machinery and mini hydro intake.',
    key_findings: 'Massive wedge failure of rock and permafrost from Annapurna IV (109M m³) dammed gorge, creating hyper-concentrated slurry that exploded downstream.'
  },
  {
    id: 'glof-melamchi-2021',
    event_name: 'Melamchi Debris Torrent & Moraine Breach (2021)',
    lake_or_glacier: 'Bhemathang Permafrost / Langtang Moraine',
    basin: 'Gandaki / Koshi',
    river: 'Melamchi River / Indrawati',
    country_region: 'Helambu / Melamchi, Sindhupalchok, Nepal',
    event_date: '2021-06-15',
    year: 2021,
    coordinates: [85.550, 28.120],
    trigger_mechanism: 'EXTREME_CLOUDBURST',
    estimated_volume_m3: 22000000,
    peak_discharge_cms: 3200,
    downstream_impact_km: 50,
    fatalities: 25,
    infrastructure_impact: 'Severe burial of the Kathmandu Melamchi Water Supply Project headworks, destroyed Melamchi Bazar, 6 motorable bridges, 200+ homes.',
    key_findings: 'Multi-hazard cascade: torrential rain saturated unstable moraine deposits at Bhemathang, sending pulses of slurry downstream over 3 weeks.'
  },
  {
    id: 'glof-kedarnath-2013',
    event_name: 'Chorabari Lake (Kedarnath) GLOF (2013)',
    lake_or_glacier: 'Chorabari Glacier / Lake',
    basin: 'Karnali-adjacent',
    river: 'Mandakini River',
    country_region: 'Kedarnath, Uttarakhand, Western Himalaya',
    event_date: '2013-06-17',
    year: 2013,
    coordinates: [79.068, 30.748],
    trigger_mechanism: 'EXTREME_CLOUDBURST',
    estimated_volume_m3: 8500000,
    peak_discharge_cms: 6000,
    downstream_impact_km: 85,
    fatalities: 5700,
    infrastructure_impact: 'Destroyed Kedarnath town, Rambara settlement, Gaurikund, damaged multiple run-of-the-river hydropower plants downstream.',
    key_findings: 'Excessive early monsoon rainfall + rapid snowmelt filled glacial tarn, leading to overtopping and moraine dam breach behind Kedarnath shrine.'
  },
  {
    id: 'glof-chamoli-2021',
    event_name: 'Chamoli Rock-Ice Detachment & Rishiganga Surge (2021)',
    lake_or_glacier: 'Raunthi Glacier / Ronti Peak',
    basin: 'Karnali-adjacent',
    river: 'Rishiganga & Dhauliganga Rivers',
    country_region: 'Chamoli, Uttarakhand',
    event_date: '2021-02-07',
    year: 2021,
    coordinates: [79.728, 30.378],
    trigger_mechanism: 'ROCK_ICE_DETACHMENT',
    estimated_volume_m3: 27000000,
    peak_discharge_cms: 8200,
    downstream_impact_km: 40,
    fatalities: 204,
    infrastructure_impact: 'Completely demolished 13.2 MW Rishiganga Hydropower Project and washed away the barrage and tunnels of 520 MW Tapovan Vishnugad Project.',
    key_findings: 'Steep permafrost wedge detachment (27M m³ rock + ice) pulverized into high-velocity debris avalanche without a pre-existing large surface lake.'
  }
];

export const MOCK_FLOOD_ALERTS: FloodAlert[] = [
  {
    id: 'a-bhotekoshi-ongoing-01',
    lake_id: 'l-galong-co',
    lake_name: 'Bhotekoshi & Upper Trishuli Corridor (Galong Co / Langtang)',
    severity: 'EMERGENCY',
    trigger_reason: 'Active debris-dam breach alert: Post-Aug 26 glacial collapse, 2.2M tonnes loose sediment, persistent upper catchment cloudbursts threatening Rasuwa & Nuwakot',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    resolved_at: null,
    affected_villages: ['Zhangmu / Kodari', 'Liping', 'Tatopani', 'Barhabise', 'Bhotekoshi Barrage'],
  },
  {
    id: 'a1111111-1111-1111-1111-111111111111',
    lake_id: 'l1111111-1111-1111-1111-111111111111',
    lake_name: 'Tsho Rolpa',
    severity: 'EMERGENCY',
    trigger_reason: 'Moraine displacement surge +18.2% expansion and 72h GPM IMERG rainfall exceeding 140mm',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    resolved_at: null,
    affected_villages: ['Na', 'Bedding', 'Chhetchhet', 'Simigaon', 'Gongar Khola'],
  },
];

export const MOCK_INSAR_TELEMETRY: any[] = [
  {
    id: 'insar-tsho-rolpa-01',
    lake_id: 'l1111111-1111-1111-1111-111111111111',
    lake_name: 'Tsho Rolpa',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -24.8,
    max_subsidence_mm_year: -36.2,
    mean_coherence: 0.78,
    deformation_rating: 'CRITICAL_DESTABILIZATION',
    points: [
      { point_id: 'pt-1', lat: 27.868, lon: 86.475, los_velocity_mm_year: -26.1, coherence: 0.81, is_anomaly: true },
      { point_id: 'pt-2', lat: 27.869, lon: 86.476, los_velocity_mm_year: -36.2, coherence: 0.72, is_anomaly: true }
    ]
  },
  {
    id: 'insar-imja-01',
    lake_id: 'l2222222-2222-2222-2222-222222222222',
    lake_name: 'Imja Tsho',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -14.2,
    max_subsidence_mm_year: -18.5,
    mean_coherence: 0.84,
    deformation_rating: 'MODERATE_CREEP',
    points: [
      { point_id: 'pt-imja-1', lat: 27.910, lon: 86.924, los_velocity_mm_year: -14.2, coherence: 0.84, is_anomaly: false }
    ]
  },
  {
    id: 'insar-lower-barun-01',
    lake_id: 'l4444444-4444-4444-4444-444444444444',
    lake_name: 'Lower Barun Lake',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -22.5,
    max_subsidence_mm_year: -31.0,
    mean_coherence: 0.76,
    deformation_rating: 'CRITICAL_DESTABILIZATION',
    points: [
      { point_id: 'pt-lb-1', lat: 27.808, lon: 87.102, los_velocity_mm_year: -22.5, coherence: 0.76, is_anomaly: true }
    ]
  },
  {
    id: 'insar-lumding-01',
    lake_id: 'l-lumding',
    lake_name: 'Lumding Tsho',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -16.8,
    max_subsidence_mm_year: -21.4,
    mean_coherence: 0.80,
    deformation_rating: 'ACCELERATING_SUBSIDENCE',
    points: [
      { point_id: 'pt-lum-1', lat: 27.765, lon: 86.612, los_velocity_mm_year: -16.8, coherence: 0.80, is_anomaly: true }
    ]
  },
  {
    id: 'insar-chamlang-01',
    lake_id: 'l-chamlang',
    lake_name: 'Chamlang Tsho (Hongu-2)',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -18.2,
    max_subsidence_mm_year: -25.6,
    mean_coherence: 0.79,
    deformation_rating: 'ACCELERATING_SUBSIDENCE',
    points: [
      { point_id: 'pt-cham-1', lat: 27.782, lon: 86.974, los_velocity_mm_year: -18.2, coherence: 0.79, is_anomaly: true }
    ]
  },
  {
    id: 'insar-dig-tsho-01',
    lake_id: 'l-dig-tsho',
    lake_name: 'Dig Tsho (1985 Breach)',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -7.5,
    max_subsidence_mm_year: -11.2,
    mean_coherence: 0.88,
    deformation_rating: 'MODERATE_CREEP',
    points: [
      { point_id: 'pt-dig-1', lat: 27.876, lon: 86.584, los_velocity_mm_year: -7.5, coherence: 0.88, is_anomaly: false }
    ]
  },
  {
    id: 'insar-galong-co-01',
    lake_id: 'l-galong-co',
    lake_name: 'Galong Co / Cirenmaco (Poiqu Transboundary)',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -28.4,
    max_subsidence_mm_year: -39.1,
    mean_coherence: 0.71,
    deformation_rating: 'CRITICAL_DESTABILIZATION',
    points: [
      { point_id: 'pt-gal-1', lat: 28.066, lon: 86.068, los_velocity_mm_year: -28.4, coherence: 0.71, is_anomaly: true }
    ]
  },
  {
    id: 'insar-thulagi-01',
    lake_id: 'l3333333-3333-3333-3333-333333333333',
    lake_name: 'Thulagi Lake',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -19.6,
    max_subsidence_mm_year: -27.8,
    mean_coherence: 0.82,
    deformation_rating: 'ACCELERATING_SUBSIDENCE',
    points: [
      { point_id: 'pt-thu-1', lat: 28.517, lon: 84.532, los_velocity_mm_year: -19.6, coherence: 0.82, is_anomaly: true }
    ]
  },
  {
    id: 'insar-birendra-01',
    lake_id: 'l-birendra',
    lake_name: 'Birendra Lake (Manaslu)',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -26.3,
    max_subsidence_mm_year: -35.4,
    mean_coherence: 0.74,
    deformation_rating: 'CRITICAL_DESTABILIZATION',
    points: [
      { point_id: 'pt-bir-1', lat: 28.563, lon: 84.638, los_velocity_mm_year: -26.3, coherence: 0.74, is_anomaly: true }
    ]
  },
  {
    id: 'insar-kaldang-01',
    lake_id: 'l-kaldang',
    lake_name: 'Kaldang Lake (Langtang)',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -11.4,
    max_subsidence_mm_year: -15.8,
    mean_coherence: 0.85,
    deformation_rating: 'MODERATE_CREEP',
    points: [
      { point_id: 'pt-kal-1', lat: 28.215, lon: 85.485, los_velocity_mm_year: -11.4, coherence: 0.85, is_anomaly: false }
    ]
  },
  {
    id: 'insar-karnali-01',
    lake_id: 'l5555555-5555-5555-5555-555555555555',
    lake_name: 'Karnali High-Alpine Glacial Lake',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -4.8,
    max_subsidence_mm_year: -6.5,
    mean_coherence: 0.91,
    deformation_rating: 'STABLE_PERMAFROST',
    points: [
      { point_id: 'pt-kar-1', lat: 29.893, lon: 82.342, los_velocity_mm_year: -4.8, coherence: 0.91, is_anomaly: false }
    ]
  },
  {
    id: 'insar-rara-01',
    lake_id: 'l-rara-headwater',
    lake_name: 'Rara Headwater Glacial Lake',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -3.9,
    max_subsidence_mm_year: -5.2,
    mean_coherence: 0.93,
    deformation_rating: 'STABLE_PERMAFROST',
    points: [
      { point_id: 'pt-rar-1', lat: 29.542, lon: 82.115, los_velocity_mm_year: -3.9, coherence: 0.93, is_anomaly: false }
    ]
  },
  {
    id: 'insar-api-01',
    lake_id: 'l-api-nampa-srv',
    lake_name: 'Api Nampa Proglacial Lake',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -5.1,
    max_subsidence_mm_year: -7.3,
    mean_coherence: 0.89,
    deformation_rating: 'STABLE_PERMAFROST',
    points: [
      { point_id: 'pt-api-1', lat: 29.980, lon: 80.950, los_velocity_mm_year: -5.1, coherence: 0.89, is_anomaly: false }
    ]
  },
  {
    id: 'insar-lhonak-01',
    lake_id: 'l-south-lhonak',
    lake_name: 'South Lhonak Lake (2023 Benchmark)',
    recorded_at: new Date().toISOString(),
    mean_los_velocity_mm_year: -31.2,
    max_subsidence_mm_year: -44.0,
    mean_coherence: 0.69,
    deformation_rating: 'CRITICAL_DESTABILIZATION',
    points: [
      { point_id: 'pt-lho-1', lat: 27.912, lon: 88.196, los_velocity_mm_year: -31.2, coherence: 0.69, is_anomaly: true }
    ]
  }
];

export const MOCK_CUE_SLEW_TASKINGS: any[] = [
  {
    tasking_id: 'task-slew-tsho-rolpa-01',
    lake_id: 'l1111111-1111-1111-1111-111111111111',
    lake_name: 'Tsho Rolpa',
    priority: 'IMMEDIATE_INTERVENTION',
    target_sensor: 'SkySat-Submeter',
    target_gsd_meters: 0.50,
    bbox: [86.45, 27.85, 86.50, 27.89],
    reasons: [
      {
        source: 'INSAR_SUBSIDENCE',
        severity: 'CRITICAL',
        description: 'Severe moraine crest subsidence -36.2 mm/yr indicates internal ice core degradation',
        observed_value: -36.2
      }
    ],
    required_cv_analyses: [
      'Tension crack propagation and shear aperture widening',
      'Dam crest piping seepage and thermokarst pond formation'
    ],
    status: 'TASKED',
    created_at: new Date().toISOString()
  }
];

export const MOCK_EDGE_SENSOR_READINGS: any[] = [
  {
    id: 'edge-gorge-tsho-01',
    station_id: 'st-rolwaling-upper',
    gorge_name: 'Rolwaling Upper Choke Gorge',
    lake_id: 'l1111111-1111-1111-1111-111111111111',
    recorded_at: new Date().toISOString(),
    geophone_dominant_freq_hz: 12.5,
    geophone_acoustic_energy_db: 36.2,
    water_stage_m: 1.45,
    water_stage_rate_m_min: 0.01,
    tripwire_status: 'INTACT',
    is_slurry_surge_detected: false,
    alarm_level: 'NORMAL',
    scada_actuation: null
  }
];

